#!/bin/bash
set -euo pipefail

swift --version

swift package dollup --allow-writing-to-package-directory
git diff --exit-code

# swift-syntax prebuilt binaries not compatible with `--explicit-target-dependency-import-check`

swift build -c release \
    --explicit-target-dependency-import-check=error \
    --disable-experimental-prebuilts \
    --build-tests

swift test -c release \
    --skip-build \
    --explicit-target-dependency-import-check=error \
    --disable-experimental-prebuilts
